from enum import Enum

class States(Enum):
    SELECT_GAME = 0
    GAME_ACTIONS = 1
    SELECT_ATTRIBUTE_TO_EDIT = 2
    EDIT_GAME_ATTRIBUTE_VALUE = 3
    REGISTER_PLAYER = 4
    REMOVE_PLAYER = 5
    SELECT_GAME_TO_EDIT = 6
    EDIT_ATTRIBUTE = 7
    EDIT_ATTRIBUTE_VALUE = 8
    EDIT_GAME_FINISH = 9
    EDIT_GAME = 10